/**
 * ========================================
 * RESTAURANTS SEED DATA
 * ========================================
 * 10 restaurants - NO VOUCHERS (as requested)
 */

import type { Restaurant } from './localStorage-manager';

export const SEED_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'Phở Hà Nội',
    slug: 'pho-ha-noi-rest-1',
    ownerId: 'user-restaurant-1', // Owned by the restaurant user account
    categories: [{ id: 'cat-vietnamese', name: 'Vietnamese', slug: 'vietnamese' }],
    status: 'ACTIVE',
    rating: 4.8,
    address: '123 Nguyễn Huệ, Q1, TP.HCM',
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800',
    description: 'Authentic Northern Vietnamese cuisine with traditional pho and street food favorites',
    reviewCount: 156,
    location: { lat: 10.7798, lng: 106.6923 },
  },
  {
    id: 'rest-2',
    name: 'Sushi Sakura',
    slug: 'sushi-sakura-rest-2',
    categories: [{ id: 'cat-japanese', name: 'Japanese', slug: 'japanese' }],
    status: 'ACTIVE',
    rating: 4.9,
    address: '456 Lê Lợi, Q1, TP.HCM',
    imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
    description: 'Premium Japanese sushi and sashimi with fresh ingredients imported daily',
    reviewCount: 203,
    location: { lat: 10.7722, lng: 106.7007 },
  },
  {
    id: 'rest-3',
    name: 'Pizza Bella Italia',
    slug: 'pizza-bella-italia-rest-3',
    categories: [{ id: 'cat-italian', name: 'Italian', slug: 'italian' }],
    status: 'ACTIVE',
    rating: 4.7,
    address: '789 Pasteur, Q3, TP.HCM',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    description: 'Authentic Italian pizzas and pastas made with imported ingredients',
    reviewCount: 120,
    location: { lat: 10.7769, lng: 106.6789 },
  },
  {
    id: 'rest-4',
    name: 'Bún Bò Huế Authentic',
    slug: 'bun-bo-hue-authentic-rest-4',
    categories: [{ id: 'cat-vietnamese', name: 'Vietnamese', slug: 'vietnamese' }],
    status: 'ACTIVE',
    rating: 4.6,
    address: '321 Võ Văn Tần, Q3, TP.HCM',
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800',
    description: 'Traditional Central Vietnamese cuisine specializing in spicy beef noodle soup',
    reviewCount: 98,
    location: { lat: 10.7745, lng: 106.7023 },
  },
  {
    id: 'rest-5',
    name: 'Café De Paris',
    slug: 'cafe-de-paris-rest-5',
    categories: [{ id: 'cat-cafe', name: 'Café', slug: 'cafe' }],
    status: 'ACTIVE',
    rating: 4.5,
    address: '654 Đồng Khởi, Q1, TP.HCM',
    imageUrl: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800',
    description: 'French-inspired café serving artisanal coffee and delicate pastries',
    reviewCount: 85,
    location: { lat: 10.7698, lng: 106.6912 },
  },
  {
    id: 'rest-6',
    name: 'Korean BBQ House',
    slug: 'korean-bbq-house-rest-6',
    categories: [{ id: 'cat-korean', name: 'Korean', slug: 'korean' }],
    status: 'ACTIVE',
    rating: 4.8,
    address: '987 Nguyễn Thị Minh Khai, Q3, TP.HCM',
    imageUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800',
    description: 'Premium Korean BBQ with all-you-can-eat options and authentic side dishes',
    reviewCount: 175,
    location: { lat: 10.7854, lng: 106.6889 },
  },
  {
    id: 'rest-7',
    name: 'Thai Spice Kitchen',
    slug: 'thai-spice-kitchen-rest-7',
    categories: [{ id: 'cat-thai', name: 'Thai', slug: 'thai' }],
    status: 'ACTIVE',
    rating: 4.7,
    address: '147 Hai Bà Trưng, Q1, TP.HCM',
    imageUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800',
    description: 'Authentic Thai flavors with the perfect balance of sweet, sour, salty, and spicy',
    reviewCount: 142,
    location: { lat: 10.7721, lng: 106.6845 },
  },
  {
    id: 'rest-8',
    name: 'Burger Brothers',
    slug: 'burger-brothers-rest-8',
    categories: [{ id: 'cat-burger', name: 'Burger', slug: 'burger' }],
    status: 'ACTIVE',
    rating: 4.6,
    address: '258 Cách Mạng Tháng 8, Q10, TP.HCM',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    description: 'Gourmet burgers made with premium beef and creative toppings',
    reviewCount: 110,
    location: { lat: 10.7723, lng: 106.6812 },
  },
  {
    id: 'rest-9',
    name: 'Dim Sum Palace',
    slug: 'dim-sum-palace-rest-9',
    categories: [{ id: 'cat-chinese', name: 'Chinese', slug: 'chinese' }],
    status: 'ACTIVE',
    rating: 4.9,
    address: '369 Nguyễn Đình Chiểu, Q3, TP.HCM',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800',
    description: 'Traditional Cantonese dim sum served in bamboo steamers with tea',
    reviewCount: 220,
    location: { lat: 10.7834, lng: 106.7089 },
  },
  {
    id: 'rest-10',
    name: 'Mediterranean Delight',
    slug: 'mediterranean-delight-rest-10',
    categories: [{ id: 'cat-mediterranean', name: 'Mediterranean', slug: 'mediterranean' }],
    status: 'ACTIVE',
    rating: 4.7,
    address: '741 Trần Hưng Đạo, Q5, TP.HCM',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    description: 'Fresh Mediterranean cuisine with healthy options and vibrant flavors',
    reviewCount: 95,
    location: { lat: 10.7689, lng: 106.6778 },
  },
];
